- name: variables in ansible
  hosts: mongodb
  # this is playlevel variables,map
  vars:
    course: Devops
    Trainer: sdk
    Duration: 110hrs
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello iam learning Ansible"
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello iam learning {{course}},Trainer is{{Trainer}},Duratio is {{Duration}}"
