- name: variables from files
  hosts: localhost #managin the ansible server itself
  vars_files:
  - variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "we are learning {{COURSE}}, Duration is {{DURATION}}, Trainer is: {{TRAINER}}"
