- name: variables precedence
  hosts: mongodb
  vars:
    NAME: Kashi-play
    DESIGNATION: jun
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter username
    private: false
  tasks:
  - name: Precedence task
    vars:
      NAME: Kashi-tasklevel
  ansible.builtin.debug:
    msg: "trainer name is: {{NAME}}"