- name: create a user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    # when you want to run linux commands directly i.e in the case ansible module not avialable
    # when the user does not exists, ansible trated it as failure and comeout by default
    # ignore_errors: true

    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"