- name: simple condition
  hosts: localhost
  vars:
    NAME: DevOps
  tasks:
  - name: run this if the name is devops
    ansible.builtin.debug:
      msg: "Hello {{NAME}}"
    when: "{{NAME}} == 'DevOps'"