- name: some packages install and some pkg's remove
  hosts: mongodb
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx',state: 'absent'}
    - {name: 'postfix',state: 'installed'}
    - {name: 'cyrus-sasl-plain',state: 'absent'}
    - {name: 'mailx',state: 'installed'}